export default {
    path:"/brand",
    component:()=>import("@pages/brand"),
    name:"brand",
    meta:{
        title:"识货发现",
        tabBarFlag:true,
        requiredAuth:false
    },
    children:[{
                path:"whole",
                component:()=>import("@pages/brand/whole/index"),
                meta:{
                    title:"全部",
                    tabBarFlag:true,
                    requiredAuth:false
                }
            },
            {
                path:"motion",
                component:()=>import("@pages/brand/whole/index"),
                meta:{
                    title:"全部",
                    tabBarFlag:true,
                    requiredAuth:false
                }
            },
            {
                path:"clothes",
                component:()=>import("@pages/brand/whole/index"),
                meta:{
                    title:"全部",
                    tabBarFlag:true,
                    requiredAuth:false
                }
            },
            {
                path:"digital",
                component:()=>import("@pages/brand/whole/index"),
                meta:{
                    title:"全部",
                    tabBarFlag:true,
                    requiredAuth:false
                }
            },
            {
                path:"other",
                component:()=>import("@pages/brand/whole/index"),
                meta:{
                    title:"全部",
                    tabBarFlag:true,
                    requiredAuth:false
                }
            },
        ]
}